version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backstage:
    image: spotify/backstage-cookiecutter
    ports:
      - "7007:7007"
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: backstage
      DATABASE_PASSWORD: backstage
      DATABASE_NAME: backstage
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - /app/node_modules

volumes:
  postgres_data:
